# Generated by Django 3.2.13 on 2023-02-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
