# Generated by Django 3.2.13 on 2023-02-27 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_childcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='image',
            new_name='cate_image',
        ),
    ]
