# Generated by Django 3.2.13 on 2023-02-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_rename_image_maincategory_cate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('used', models.CharField(max_length=20)),
            ],
        ),
    ]
