# Generated by Django 3.2.13 on 2023-02-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='amount',
            field=models.CharField(max_length=20),
        ),
    ]
