# Generated by Django 3.2.13 on 2023-03-02 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
