# Generated by Django 3.2.13 on 2023-03-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='amount',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
