# Generated by Django 3.2.13 on 2023-03-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_auto_20230302_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='product'),
            preserve_default=False,
        ),
    ]
