# Generated by Django 3.2.13 on 2023-03-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='cate_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
