# Generated by Django 3.2.13 on 2023-03-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_alter_maincategory_cate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='cate_image',
            field=models.ImageField(max_length=255, upload_to='media/'),
        ),
    ]
