# Generated by Django 3.2.16 on 2022-12-28 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0003_wishlist_sellint_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='sellint_price',
            new_name='selling_price',
        ),
    ]
