# Generated by Django 3.2.13 on 2023-02-20 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0007_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='addtocartmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='addtocartmodel',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ecomm_app.product'),
            preserve_default=False,
        ),
    ]
