# Generated by Django 3.2.13 on 2023-02-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0009_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
