# Generated by Django 3.2.13 on 2023-02-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0013_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocartmodel',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecomm_app.product'),
        ),
        migrations.AlterField(
            model_name='addtocartmodel',
            name='qty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.CharField(max_length=20),
        ),
    ]
