# Generated by Django 3.2.13 on 2023-02-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0014_auto_20230220_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocartmodel',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
