# Generated by Django 3.2.13 on 2023-02-21 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0015_alter_addtocartmodel_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='title',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecomm_app.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
