# Generated by Django 3.2.13 on 2023-02-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0019_auto_20230221_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocartmodel',
            name='qty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
