# Generated by Django 3.2.13 on 2023-02-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0020_alter_addtocartmodel_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocartmodel',
            name='qty',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
