# Generated by Django 3.2.13 on 2023-02-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0025_auto_20230221_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocartmodel',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ecomm_app.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addtocartmodel',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
