# Generated by Django 3.2.13 on 2023-02-21 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0026_auto_20230221_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocartmodel',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecomm_app.product'),
        ),
    ]
