# Generated by Django 3.2.13 on 2023-02-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0028_alter_addtocartmodel_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='addtocartmodel',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecomm_app.product'),
        ),
    ]
