# Generated by Django 3.2.13 on 2023-02-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0029_auto_20230221_1310'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainCategory',
        ),
    ]
