# Generated by Django 3.2.13 on 2023-02-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0030_delete_maincategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
