# Generated by Django 3.2.13 on 2023-02-28 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0031_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomm_app.user')),
            ],
        ),
    ]
