# Generated by Django 3.2.13 on 2023-02-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm_app', '0032_productreviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewmodel',
            name='reviewer',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ProductCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomm_app.userregistration')),
            ],
        ),
    ]
